import React from 'react';
import type { Metadata } from 'next';
import type { AppProps } from 'next/app';
import { Inter } from 'next/font/google';
import '@/app/globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  Component,
  pageProps,
}: AppProps) {
  return (
    <div id="hello">
      <Component {...pageProps} />
    </div>
  );
}
